<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

$identity = $this->identity();

if ($identity) {
    /** @var int $identifier */
    $identifier = 'SOME_RELATION';

    /** @var string $relation */
    $relation = 'SOME_RELATION[100500]';

    /** @var \MSBios\Voting\Resource\Doctrine\Entity\Poll $poll */
    $poll = $this->poll()->find($identifier, $relation);

    /** @var array $variants */
    $variants = $this->poll()->variants($poll);

    /** @var boolean $isVoted */
    $isVoted = $this->poll()->check($poll);
}

?>

<?php /** @var \Zend\View\Helper\FlashMessenger $flash */ ?>
<?php $flash = $this->flashMessenger(); ?>

<?php if ($flash->hasSuccessMessages()) : ?>

    <div class="alert alert-success no-border">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <span class="text-semibold"><?= $this->translate('Success!'); ?></span>
        <?= implode(', ', $flash->getSuccessMessages()); ?>
    </div>

<?php elseif ($flash->hasInfoMessages()) : ?>

    <div class="alert alert-info no-border">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <span class="text-semibold"><?= $this->translate('Success!'); ?></span>
        <?= implode(', ', $flash->getInfoMessages()); ?>
    </div>

<?php endif; ?>

<?php if ($flash->hasWarningMessages()) : ?>

    <div class="alert alert-danger no-border">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <span class="text-semibold"><?= $this->translate('Warning!'); ?></span>
        <?= implode(', ', $flash->getWarningMessages()); ?>
    </div>

<?php endif; ?>

<?php if ($identity): ?>
    <h1>
        <?= $poll->getSubject(); ?><br>
        <small class="text-muted">
            <b>Total Votes:</b>
            <small><?= $poll->getTotal(); ?></small>
            <b>Avg:</b>
            <small><?= number_format($poll->getAvg(), 2); ?></small>
        </small>
    </h1>
    <?php

    /** @var \Zend\Form\FormInterface $form */
    $form = $this->form;
    $form->setData([
        'poll_relation' => $poll->getCode(),
        'poll_identifier' => $poll->getPoll()->getId()
    ]);
    $form->setAttribute('action', $this->url('home/voting'));
    $form->prepare();

    ?>

    <div style="margin-bottom: 20px;">
        <?php if (!$isVoted) : ?>
            <?= $this->form()->openTag($form); ?>
            <ul>
                <?php $element = $form->get('poll_option_identifier'); ?>

                <?php foreach ($variants as $variant): ?>
                    <li>
                        <label>
                            <?php if (!$isVoted): ?>
                                <?= $this->formRadio(new \Zend\Form\Element\Radio($element->getName(), [
                                    'value_options' => [[
                                        'value' => $variant['id'],
                                    ]]
                                ])); ?>
                            <?php endif; ?>
                            <?= $variant['name']; ?>
                        </label>
                        <small>
                            Total: <?= $variant['total']; ?>
                            Percents: <?= number_format($variant['percent'], 2); ?>%
                        </small>

                    </li>
                <?php endforeach; ?>
            </ul>
            <?= $this->formElement($form->get('poll_relation')); ?>
            <?= $this->formElement($form->get('poll_redirect')); ?>
            <?= $this->formButton($form->get('poll_identifier')->setAttribute('class', 'btn btn-default')->setLabel('Button')); ?>
            <?= $this->form()->closeTag($form); ?>
        <?php else: ?>
            <ul>
                <?php foreach ($variants as $variant): ?>
                    <li>
                        <label>
                            <?= $variant['name']; ?>
                        </label>
                        <small>
                            Total: <?= $variant['total']; ?>
                            Percents: <?= number_format($variant['percent'], 2); ?>%
                        </small>
                    </li>
                <?php endforeach; ?>
            </ul>

            <?= r($this->poll()->getVoteManager()->find($poll)); ?>

            <a href="#" class="btn btn-link">
                Change voice
            </a>
        <?php endif; ?>
    </div>
<?php else: ?>
    <h1>Authentication</h1>

    <form method="POST" action="<?= $this->url('home/login'); ?>" class="row">
        <div class="panel panel-body col-md-3">
            <div class="form-group has-feedback has-feedback-left">
                <input type="text" name="username" class="form-control" placeholder="Username" value="">
            </div>

            <div class="form-group has-feedback has-feedback-left">
                <input type="password" name="password" class="form-control" placeholder="Password" value="">
            </div>

            <div class="form-group">
                <input type="hidden" name="redirect" value="">
                <button type="submit" class="btn btn-primary">
                    Sign in <i class="icon-circle-right2 position-right"></i>
                </button>
            </div>
        </div>
    </form>

<?php endif; ?>

<ul>
    <li>Vote Module version: <?= \MSBios\Voting\Module::VERSION; ?></li>
    <li>Vote Resource Module version: <?= \MSBios\Voting\Resource\Module::VERSION; ?></li>
    <li>Vote Doctrine Module version: <?= \MSBios\Voting\Doctrine\Module::VERSION; ?></li>
    <li>Vote Resource Doctrine Module version: <?= \MSBios\Voting\Resource\Doctrine\Module::VERSION; ?></li>
    <li>Vote Authentication Doctrine Module version: <?= \MSBios\Voting\Authentication\Doctrine\Module::VERSION; ?></li>
    <li>Vote Authentication Resource Doctrine Module version: <?= \MSBios\Voting\Authentication\Resource\Doctrine\Module::VERSION; ?></li>
</ul>